name: 刷步数

on:
  schedule:
    - cron: '30 0,4,7,10,12,14 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        
      - name: 更新系统并安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
          
      - name: 设置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 安装Python依赖
        run: pip3 install requests
        
      - name: 执行主程序
        run: |
          user="${{ secrets.USER }}"
          passwd="${{ secrets.PWD }}" 
          open_get_weather="${{ secrets.OPEN_GET_WEATHER }}"
          area="${{ secrets.AREA }}"
          
          # 检查必要的密钥是否存在
          if [ -z "$user" ] || [ -z "$passwd" ]; then
            echo "错误：必须设置 USER 和 PWD 密钥"
            exit 1
          fi
          
          python3 main.py "$user" "$passwd" "$open_get_weather" "$area"
